# Generated by Django 3.1.3 on 2020-11-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_remove_conference_submission_deadline'),
        ('cfp', '0002_conferencecfp_cfp_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencecfp',
            name='conference_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cfp', to='conference.conference'),
        ),
    ]
