# Generated by Django 3.1.3 on 2020-11-27 14:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0002_remove_conference_submission_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePCMInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateField(default=datetime.date.today)),
                ('role', models.CharField(choices=[('1', 'chair'), ('2', 'member')], default='2', max_length=1)),
                ('accepted', models.BooleanField(default=False)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_invitation', to='conference.conference')),
                ('invitee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
