# Generated by Django 3.1.3 on 2020-11-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conferencepcminvitations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencepcminvitations',
            old_name='conference_id',
            new_name='conference',
        ),
    ]
