# Generated by Django 3.1.3 on 2020-11-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20201129_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepcminvitations',
            name='invitee',
            field=models.EmailField(max_length=254),
        ),
    ]
