# Generated by Django 3.1.3 on 2020-12-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20201202_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepcminvitations',
            name='role',
            field=models.IntegerField(choices=[(1, 'chair'), (2, 'member')], default=2),
        ),
    ]
