# Generated by Django 3.1.3 on 2020-12-02 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_auto_20201202_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 2, 16, 1, 49, 40540, tzinfo=utc), help_text='Enter the end date of the conference'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 2, 16, 1, 49, 40510, tzinfo=utc), help_text='Enter the start date of the conference'),
        ),
        migrations.AlterField(
            model_name='conferencepcminvitations',
            name='invitation_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 16, 1, 49, 41952, tzinfo=utc)),
        ),
    ]
