# Generated by Django 3.1.3 on 2021-01-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_auto_20201202_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='phase',
            field=models.CharField(blank=True, default='Registration', max_length=100),
        ),
    ]
