# Generated by Django 3.1.3 on 2021-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20210104_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='phase',
            field=models.IntegerField(choices=[(0, 'registration'), (1, 'submission'), (2, 'review'), (3, 'discussion'), (4, 'notification')], default=0),
        ),
    ]
