# Generated by Django 3.1.3 on 2021-01-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0013_auto_20210104_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=1000)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper_file', models.FileField(upload_to='')),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
