# Generated by Django 3.1.3 on 2021-01-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_conferencesubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesubmissions',
            name='conference',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='conference.conference'),
            preserve_default=False,
        ),
    ]
