# Generated by Django 3.1.3 on 2021-01-06 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_auto_20210106_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepcminvitations',
            name='invitation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conferencesubmissions',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
