# Generated by Django 3.1.3 on 2021-01-15 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0017_auto_20210106_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesubmissions',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
