# Generated by Django 3.1.3 on 2021-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_auto_20210119_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceuserroles',
            name='role',
            field=models.CharField(choices=[(1, 'chair'), (2, 'reviewer'), (3, 'author')], max_length=10),
        ),
    ]
