# Generated by Django 3.1.3 on 2021-01-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_auto_20210119_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='phase',
            field=models.IntegerField(choices=[(1, 'registration'), (2, 'submission'), (3, 'review'), (4, 'discussion'), (5, 'notification')], default=1),
        ),
        migrations.AlterField(
            model_name='conferenceuserroles',
            name='role',
            field=models.IntegerField(choices=[(2, 'reviewer'), (3, 'author'), (1, 'chair')], max_length=2),
        ),
    ]
