# Generated by Django 3.1.3 on 2021-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0026_auto_20210122_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(5, 'very high'), (2, 'low'), (4, 'high'), (1, 'very low'), (3, 'normal')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-1, 'weak reject'), (2, 'strong accept'), (0, 'borderline paper'), (1, 'weak accept'), (-2, 'strong reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'reviewer'), (3, 'author'), (1, 'chair')]),
        ),
    ]
