# Generated by Django 3.1.3 on 2021-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0027_auto_20210122_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(3, 'normal'), (4, 'high'), (2, 'low'), (1, 'very low'), (5, 'very high')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-2, 'strong reject'), (-1, 'weak reject'), (1, 'weak accept'), (0, 'borderline paper'), (2, 'strong accept')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (1, 'chair'), (2, 'reviewer')]),
        ),
    ]
