# Generated by Django 3.1.3 on 2021-01-25 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0028_auto_20210122_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesubmissionreview',
            name='review_reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(1, 'very low'), (5, 'very high'), (3, 'normal'), (2, 'low'), (4, 'high')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (2, 'reviewer'), (1, 'chair')]),
        ),
    ]
