# Generated by Django 3.1.3 on 2021-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_auto_20210125_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(4, 'high'), (5, 'very high'), (2, 'low'), (3, 'normal'), (1, 'very low')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-2, 'strong reject'), (-1, 'weak reject'), (2, 'strong accept'), (0, 'borderline paper'), (1, 'weak accept')]),
        ),
    ]
