# Generated by Django 3.1.3 on 2021-01-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0031_auto_20210125_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesubmissionreview',
            name='review_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(5, 'very high'), (2, 'low'), (1, 'very low'), (4, 'high'), (3, 'normal')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(1, 'weak accept'), (-2, 'strong reject'), (0, 'borderline paper'), (-1, 'weak reject'), (2, 'strong accept')]),
        ),
        migrations.CreateModel(
            name='ConferenceSubmissionDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_text', models.TextField()),
                ('discussion_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('discussion_conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_conference', to='conference.conference')),
                ('discussion_reviewer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_reviewer', to=settings.AUTH_USER_MODEL)),
                ('discussion_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_submission', to='conference.conferencesubmission')),
            ],
        ),
    ]
