# Generated by Django 3.1.3 on 2021-01-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0032_auto_20210125_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencesubmissiondiscussion',
            old_name='discussion_time',
            new_name='discussion_date_time',
        ),
        migrations.RenameField(
            model_name='conferencesubmissionreview',
            old_name='review_time',
            new_name='review_date_time',
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(4, 'high'), (3, 'normal'), (1, 'very low'), (5, 'very high'), (2, 'low')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-2, 'strong reject'), (1, 'weak accept'), (2, 'strong accept'), (-1, 'weak reject'), (0, 'borderline paper')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (2, 'reviewer'), (1, 'chair')]),
        ),
    ]
