# Generated by Django 3.1.3 on 2021-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0036_auto_20210125_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'permissions': (('chair', 'Chair'), ('reviewer', 'Reviewer'))},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmission',
            options={'permissions': (('chair', 'Chair'), ('reviewer', 'Reviewer'), ('author', 'Author'))},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmissiondiscussion',
            options={'ordering': ['discussion_date_time'], 'permissions': (('chair', 'Chair'), ('reviewer', 'Reviewer'), ('author', 'Author'))},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmissionreview',
            options={'ordering': ['review_date_time'], 'permissions': (('chair', 'Chair'), ('reviewer', 'Reviewer'), ('author', 'Author'))},
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(1, 'very low'), (5, 'very high'), (2, 'low'), (4, 'high'), (3, 'normal')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-1, 'weak reject'), (2, 'strong accept'), (1, 'weak accept'), (-2, 'strong reject'), (0, 'borderline paper')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'reviewer'), (3, 'author'), (1, 'chair')]),
        ),
    ]
