# Generated by Django 3.1.3 on 2021-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0037_auto_20210125_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='PCM',
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(4, 'high'), (1, 'very low'), (3, 'normal'), (5, 'very high'), (2, 'low')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(1, 'weak accept'), (2, 'strong accept'), (-1, 'weak reject'), (0, 'borderline paper'), (-2, 'strong reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'reviewer'), (1, 'chair'), (3, 'author')]),
        ),
    ]
