# Generated by Django 3.1.3 on 2021-01-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0038_auto_20210125_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(3, 'normal'), (4, 'high'), (1, 'very low'), (2, 'low'), (5, 'very high')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(0, 'borderline paper'), (-2, 'strong reject'), (-1, 'weak reject'), (1, 'weak accept'), (2, 'strong accept')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (2, 'reviewer'), (1, 'chair')]),
        ),
    ]
