# Generated by Django 3.1.3 on 2021-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0041_auto_20210126_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(2, 'low'), (5, 'very high'), (1, 'very low'), (4, 'high'), (3, 'normal')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(0, 'borderline paper'), (1, 'weak accept'), (-2, 'strong reject'), (-1, 'weak reject'), (2, 'strong accept')]),
        ),
    ]
