# Generated by Django 3.1.3 on 2021-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0042_auto_20210126_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmissiondiscussion',
            options={'ordering': ['discussion_date_time']},
        ),
        migrations.AlterModelOptions(
            name='conferencesubmissionreview',
            options={'ordering': ['review_date_time']},
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(4, 'high'), (5, 'very high'), (3, 'normal'), (1, 'very low'), (2, 'low')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(2, 'strong accept'), (-2, 'strong reject'), (0, 'borderline paper'), (1, 'weak accept'), (-1, 'weak reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'chair'), (3, 'author'), (2, 'reviewer')]),
        ),
    ]
