# Generated by Django 3.1.3 on 2021-01-27 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0043_auto_20210126_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(2, 'low'), (1, 'very low'), (3, 'normal'), (4, 'high'), (5, 'very high')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(0, 'borderline paper'), (-1, 'weak reject'), (-2, 'strong reject'), (2, 'strong accept'), (1, 'weak accept')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (2, 'reviewer'), (1, 'chair')]),
        ),
        migrations.AlterUniqueTogether(
            name='conferencepcminvitation',
            unique_together={('conference', 'invitee', 'role')},
        ),
    ]
