# Generated by Django 3.1.3 on 2021-01-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0044_auto_20210127_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencepcminvitation',
            options={'ordering': ['role']},
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(1, 'very low'), (5, 'very high'), (4, 'high'), (3, 'normal'), (2, 'low')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(-1, 'weak reject'), (0, 'borderline paper'), (2, 'strong accept'), (1, 'weak accept'), (-2, 'strong reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(3, 'author'), (1, 'chair'), (2, 'reviewer')]),
        ),
    ]
