# Generated by Django 3.1.3 on 2021-01-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0045_auto_20210127_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencepcminvitation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conferenceuserrole',
            options={'ordering': ['role']},
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(5, 'very high'), (2, 'low'), (3, 'normal'), (1, 'very low'), (4, 'high')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(0, 'borderline paper'), (-2, 'strong reject'), (2, 'strong accept'), (1, 'weak accept'), (-1, 'weak reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'chair'), (2, 'reviewer'), (3, 'author')]),
        ),
    ]
