# Generated by Django 3.1.3 on 2021-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0046_auto_20210127_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(5, 'very high'), (1, 'very low'), (2, 'low'), (3, 'normal'), (4, 'high')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(2, 'strong accept'), (-2, 'strong reject'), (1, 'weak accept'), (0, 'borderline paper'), (-1, 'weak reject')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'reviewer'), (1, 'chair'), (3, 'author')]),
        ),
    ]
