# Generated by Django 3.1.3 on 2021-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0047_auto_20210128_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesubmission',
            name='decision',
            field=models.IntegerField(choices=[(1, 'accept'), (2, 'reject'), (3, 'pending')], default=3),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_confidence',
            field=models.IntegerField(choices=[(2, 'low'), (5, 'very high'), (4, 'high'), (1, 'very low'), (3, 'normal')]),
        ),
        migrations.AlterField(
            model_name='conferencesubmissionreview',
            name='review_score',
            field=models.IntegerField(choices=[(0, 'borderline paper'), (-2, 'strong reject'), (-1, 'weak reject'), (1, 'weak accept'), (2, 'strong accept')]),
        ),
        migrations.AlterField(
            model_name='conferenceuserrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'chair'), (3, 'author'), (2, 'reviewer')]),
        ),
    ]
